In [1]:
import pandas as pd
import datetime

In [3]:
#load the file
ocean = pd.read_csv("/Users/nisha/UMD/Data Challenge2/Data_Level5_BAH_OceanCleanup.csv", low_memory=False)

In [4]:
#top 10 rows of the dataset
ocean.head()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Other Trash (Clean Swell),Condoms,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected
0,86,"Cuyahoga County, OH, USA","Ohio, USA",United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",12/22/2014,NaN,1.0,0.0,...,0,0,0,0,0,0,0,0,0,3.0
1,87,"Fairfax County, VA, USA","Virginia, USA",United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",12/24/2014,NaN,1.0,0.0,...,0,0,0,0,0,0,0,0,2,10.0
2,92,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.04405","Land (beach, shoreline and inland)",2/19/2015,NaN,1.0,0.0,...,1,0,0,0,0,0,0,0,0,4.0
3,93,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2/19/2015,NaN,1.0,0.0,...,0,0,0,0,0,0,0,0,0,14.0
4,94,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2/19/2015,NaN,1.0,0.0,...,0,0,0,0,0,0,0,0,0,14.0

In [5]:
#bottom ten rows of the dataset
ocean.tail()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Other Trash (Clean Swell),Condoms,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected
37899,96515,"Broward County, FL, USA","Florida, USA",United States,"26.192071595116, -80.095065761509","Land (beach, shoreline and inland)",9/21/2019,Lauderdale By The Sea at El Prado Park,173.0,0.0,...,0,2,2,2,4,0,194,35,652,1830.0
37900,96516,"Broward County, FL, USA","Florida, USA",United States,"26.167607025494, -80.098590082316","Land (beach, shoreline and inland)",9/21/2019,Fort Lauderdale at Earl Lifshey Park,79.0,0.0,...,0,26,2,0,4,0,80,12,60,2370.0
37901,96517,"Broward County, FL, USA","Florida, USA",United States,"26.141126021262, -80.103590059501","Land (beach, shoreline and inland)",9/21/2019,Hugh Taylor Birch State Park,135.0,0.0,...,0,15,6,5,23,0,141,25,1171,3788.0
37902,96518,"Humboldt County, CA, USA","California, USA",United States,"40.809835251824, -124.14836608941","Land (beach, shoreline and inland)",9/21/2019,Caltrans- ZWCCD 2019,16.0,4.0,...,0,6,2,22,3,0,65,92,932,4205.0
37903,Totals:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,352468,15327,14429,11342,25685,40516,3292299,542969,2993124,NaN

In [6]:
#get the number of rows and columns
ocean.shape

(37904, 61)

In [7]:
#descriptive statistics
ocean.describe()

,Adults,Children,People,Pounds,Miles,# of bags,Cigarette Butts,"Food Wrappers (candy, chips, etc.)",Take Out/Away Containers (Plastic),Take Out/Away Containers (Foam),...,Other Trash (Clean Swell),Condoms,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected
count,37903.000000,37903.000000,37903.000000,37903.000000,37903.000000,37903.000000,3.790400e+04,3.790400e+04,37904.000000,37904.000000,...,37904.000000,37904.000000,37904.000000,37904.000000,37904.000000,37904.000000,3.790400e+04,37904.000000,3.790400e+04,37903.000000
mean,16.621481,2.452814,19.074295,310.799010,1.426367,7.360103,1.749690e+02,6.619354e+01,11.831838,8.680614,...,18.597932,0.808727,0.761344,0.598459,1.355266,2.137822,1.737178e+02,28.649694,1.579318e+02,502.647284
std,200.761902,18.684501,203.218661,4621.795387,15.329109,157.094929,1.704443e+04,6.445898e+03,1153.418164,846.008907,...,1810.697419,78.887605,74.457778,58.585591,132.347617,208.136822,1.719248e+04,2792.134959,1.539350e+04,4060.754999
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,1.000000,0.000000,1.000000,1.450000,0.027500,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,19.000000
50%,2.000000,0.000000,2.000000,5.600000,0.341700,0.000000,4.000000e+00,5.000000e+00,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,8.000000e+00,84.000000
75%,6.000000,0.000000,7.000000,24.000000,1.105100,0.000000,3.000000e+01,1.900000e+01,3.000000,2.000000,...,8.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000,4.300000e+01,264.000000
max,22060.000000,1291.000000,22060.000000,425025.000000,2423.166700,18581.000000,3.316012e+06,1.254500e+06,224237.000000,164515.000000,...,352468.000000,15327.000000,14429.000000,11342.000000,25685.000000,40516.000000,3.292299e+06,542969.000000,2.993124e+06,440496.000000

In [8]:
#get the variable names
ocean.columns

Index(['Cleanup ID', 'Zone', 'State', 'Country', 'GPS', 'Cleanup Type',
       'Cleanup Date', 'Group Name', 'Adults', 'Children', 'People', 'Pounds',
       'Miles', '# of bags', 'Cigarette Butts',
       'Food Wrappers (candy, chips, etc.)',
       'Take Out/Away Containers (Plastic)', 'Take Out/Away Containers (Foam)',
       'Bottle Caps (Plastic)', 'Bottle Caps (Metal)', 'Lids (Plastic)',
       'Straws, Stirrers', 'Forks, Knives, Spoons',
       'Beverage Bottles (Plastic)', 'Beverage Bottles (Glass)',
       'Beverage Cans', 'Grocery Bags (Plastic)', 'Other Plastic Bags',
       'Paper Bags', 'Cups, Plates (Paper)', 'Cups, Plates (Plastic)',
       'Cups, Plates (Foam)', 'Fishing Buoys, Pots & Traps',
       'Fishing Net & Pieces', 'Fishing Line (1 yard/meter = 1 piece)',
       'Rope (1 yard/meter = 1 piece)', 'Fishing Gear (Clean Swell)',
       '6-Pack Holders', 'Other Plastic/Foam Packaging',
       'Other Plastic Bottles (oil, bleach, etc.)', 'Strapping Bands',
       'Tobacco Packaging/Wrap', 'Other Packaging (Clean Swell)',
       'Appliances (refrigerators, washers, etc.)', 'Balloons', 'Cigar Tips',
       'Cigarette Lighters', 'Construction Materials', 'Fireworks', 'Tires',
       'Toys', 'Other Trash (Clean Swell)', 'Condoms', 'Diapers', 'Syringes',
       'Tampons/Tampon Applicators', 'Personal Hygiene (Clean Swell)',
       'Foam Pieces', 'Glass Pieces', 'Plastic Pieces',
       'Total Items Collected'],
      dtype='object')

In [9]:
#get the number of observations for each variable
ocean.count()

Cleanup ID                        37904
Zone                              37665
State                             37577
Country                           37903
GPS                               37903
                                  ...
Personal Hygiene (Clean Swell)    37904
Foam Pieces                       37904
Glass Pieces                      37904
Plastic Pieces                    37904
Total Items Collected             37903
Length: 61, dtype: int64

In [10]:
#finding the percentage of missing values
missing_rows = ocean.isnull().sum()/ocean.shape[0]
missing_rows

Cleanup ID                        0.000000
Zone                              0.006305
State                             0.008627
Country                           0.000026
GPS                               0.000026
                                    ...
Personal Hygiene (Clean Swell)    0.000000
Foam Pieces                       0.000000
Glass Pieces                      0.000000
Plastic Pieces                    0.000000
Total Items Collected             0.000026
Length: 61, dtype: float64

In [11]:
ocean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37904 entries, 0 to 37903
Data columns (total 61 columns):
Cleanup ID                                   37904 non-null object
Zone                                         37665 non-null object
State                                        37577 non-null object
Country                                      37903 non-null object
GPS                                          37903 non-null object
Cleanup Type                                 37903 non-null object
Cleanup Date                                 37903 non-null object
Group Name                                   26636 non-null object
Adults                                       37903 non-null float64
Children                                     37903 non-null float64
People                                       37903 non-null float64
Pounds                                       37903 non-null float64
Miles                                        37903 non-null float64
# of bags                                    37903 non-null float64
Cigarette Butts                              37904 non-null int64
Food Wrappers (candy, chips, etc.)           37904 non-null int64
Take Out/Away Containers (Plastic)           37904 non-null int64
Take Out/Away Containers (Foam)              37904 non-null int64
Bottle Caps (Plastic)                        37904 non-null int64
Bottle Caps (Metal)                          37904 non-null int64
Lids (Plastic)                               37904 non-null int64
Straws, Stirrers                             37904 non-null int64
Forks, Knives, Spoons                        37904 non-null int64
Beverage Bottles (Plastic)                   37904 non-null int64
Beverage Bottles (Glass)                     37904 non-null int64
Beverage Cans                                37904 non-null int64
Grocery Bags (Plastic)                       37904 non-null int64
Other Plastic Bags                           37904 non-null int64
Paper Bags                                   37904 non-null int64
Cups, Plates (Paper)                         37904 non-null int64
Cups, Plates (Plastic)                       37904 non-null int64
Cups, Plates (Foam)                          37904 non-null int64
Fishing Buoys, Pots & Traps                  37904 non-null int64
Fishing Net & Pieces                         37904 non-null int64
Fishing Line (1 yard/meter = 1 piece)        37904 non-null int64
Rope (1 yard/meter = 1 piece)                37904 non-null int64
Fishing Gear (Clean Swell)                   37904 non-null int64
6-Pack Holders                               37904 non-null int64
Other Plastic/Foam Packaging                 37904 non-null int64
Other Plastic Bottles (oil, bleach, etc.)    37904 non-null int64
Strapping Bands                              37904 non-null int64
Tobacco Packaging/Wrap                       37904 non-null int64
Other Packaging (Clean Swell)                37904 non-null int64
Appliances (refrigerators, washers, etc.)    37904 non-null int64
Balloons                                     37904 non-null int64
Cigar Tips                                   37904 non-null int64
Cigarette Lighters                           37904 non-null int64
Construction Materials                       37904 non-null int64
Fireworks                                    37904 non-null int64
Tires                                        37904 non-null int64
Toys                                         37904 non-null int64
Other Trash (Clean Swell)                    37904 non-null int64
Condoms                                      37904 non-null int64
Diapers                                      37904 non-null int64
Syringes                                     37904 non-null int64
Tampons/Tampon Applicators                   37904 non-null int64
Personal Hygiene (Clean Swell)               37904 non-null int64
Foam Pieces                                  37904 non-null int64
Glass Pieces                                 37904 non-null int64
Plastic Pieces                               37904 non-null int64
Total Items Collected                        37903 non-null float64
dtypes: float64(7), int64(46), object(8)
memory usage: 17.6+ MB

In [12]:
# drop the rows which has year more than 2020
ocean.drop(ocean[ocean['Cleanup Date'] == '0218-04-20'].index, inplace=True)
ocean['Cleanup Date'] = pd.to_datetime(ocean['Cleanup Date'])
ocean['Year'] = pd.DatetimeIndex(ocean['Cleanup Date']).year
ocean.drop(ocean[ocean['Year'] > 2020].index, inplace=True)

In [13]:
ocean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37894 entries, 0 to 37903
Data columns (total 62 columns):
Cleanup ID                                   37894 non-null object
Zone                                         37655 non-null object
State                                        37567 non-null object
Country                                      37893 non-null object
GPS                                          37893 non-null object
Cleanup Type                                 37893 non-null object
Cleanup Date                                 37893 non-null datetime64[ns]
Group Name                                   26631 non-null object
Adults                                       37893 non-null float64
Children                                     37893 non-null float64
People                                       37893 non-null float64
Pounds                                       37893 non-null float64
Miles                                        37893 non-null float64
# of bags                                    37893 non-null float64
Cigarette Butts                              37894 non-null int64
Food Wrappers (candy, chips, etc.)           37894 non-null int64
Take Out/Away Containers (Plastic)           37894 non-null int64
Take Out/Away Containers (Foam)              37894 non-null int64
Bottle Caps (Plastic)                        37894 non-null int64
Bottle Caps (Metal)                          37894 non-null int64
Lids (Plastic)                               37894 non-null int64
Straws, Stirrers                             37894 non-null int64
Forks, Knives, Spoons                        37894 non-null int64
Beverage Bottles (Plastic)                   37894 non-null int64
Beverage Bottles (Glass)                     37894 non-null int64
Beverage Cans                                37894 non-null int64
Grocery Bags (Plastic)                       37894 non-null int64
Other Plastic Bags                           37894 non-null int64
Paper Bags                                   37894 non-null int64
Cups, Plates (Paper)                         37894 non-null int64
Cups, Plates (Plastic)                       37894 non-null int64
Cups, Plates (Foam)                          37894 non-null int64
Fishing Buoys, Pots & Traps                  37894 non-null int64
Fishing Net & Pieces                         37894 non-null int64
Fishing Line (1 yard/meter = 1 piece)        37894 non-null int64
Rope (1 yard/meter = 1 piece)                37894 non-null int64
Fishing Gear (Clean Swell)                   37894 non-null int64
6-Pack Holders                               37894 non-null int64
Other Plastic/Foam Packaging                 37894 non-null int64
Other Plastic Bottles (oil, bleach, etc.)    37894 non-null int64
Strapping Bands                              37894 non-null int64
Tobacco Packaging/Wrap                       37894 non-null int64
Other Packaging (Clean Swell)                37894 non-null int64
Appliances (refrigerators, washers, etc.)    37894 non-null int64
Balloons                                     37894 non-null int64
Cigar Tips                                   37894 non-null int64
Cigarette Lighters                           37894 non-null int64
Construction Materials                       37894 non-null int64
Fireworks                                    37894 non-null int64
Tires                                        37894 non-null int64
Toys                                         37894 non-null int64
Other Trash (Clean Swell)                    37894 non-null int64
Condoms                                      37894 non-null int64
Diapers                                      37894 non-null int64
Syringes                                     37894 non-null int64
Tampons/Tampon Applicators                   37894 non-null int64
Personal Hygiene (Clean Swell)               37894 non-null int64
Foam Pieces                                  37894 non-null int64
Glass Pieces                                 37894 non-null int64
Plastic Pieces                               37894 non-null int64
Total Items Collected                        37893 non-null float64
Year                                         37893 non-null float64
dtypes: datetime64[ns](1), float64(8), int64(46), object(7)
memory usage: 18.2+ MB

In [14]:
# creating month, year, weekday
ocean['Month'] = pd.DatetimeIndex(ocean['Cleanup Date']).month
ocean['Weekday'] = pd.DatetimeIndex(ocean['Cleanup Date']).weekday
ocean['Day'] = pd.DatetimeIndex(ocean['Cleanup Date']).day

In [15]:
ocean.head()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Year,Month,Weekday,Day
0,86,"Cuyahoga County, OH, USA","Ohio, USA",United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",2014-12-22,NaN,1.0,0.0,...,0,0,0,0,0,3.0,2014.0,12.0,0.0,22.0
1,87,"Fairfax County, VA, USA","Virginia, USA",United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",2014-12-24,NaN,1.0,0.0,...,0,0,0,0,2,10.0,2014.0,12.0,2.0,24.0
2,92,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.04405","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,4.0,2015.0,2.0,3.0,19.0
3,93,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,14.0,2015.0,2.0,3.0,19.0
4,94,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,14.0,2015.0,2.0,3.0,19.0

In [16]:
#most frequently done cleanup type
ocean["Cleanup Type"].value_counts()

Land (beach, shoreline and inland)                  37106
Watercraft (powerboat, sailboat, kayak or canoe)      571
Underwater                                            216
Name: Cleanup Type, dtype: int64

In [17]:
#the number of times ocean cleanup done in each state
ocean["State"].value_counts()

Florida, USA                 11317
California, USA               9268
North Carolina, USA           1798
Washington, USA               1233
New York, USA                 1179
South Carolina, USA           1168
Texas, USA                    1070
Virginia, USA                 1068
Oregon, USA                    936
Hawaii, USA                    749
Massachusetts, USA             616
Pennsylvania, USA              596
Rhode Island, USA              499
Ohio, USA                      499
Illinois, USA                  482
New Jersey, USA                470
Maryland, USA                  467
Michigan, USA                  442
Connecticut, USA               407
Maine, USA                     398
District of Columbia, USA      371
Louisiana, USA                 363
Georgia, USA                   345
Delaware, USA                  331
Wisconsin, USA                 296
Alabama, USA                   197
Alaska, USA                    163
Colorado, USA                  132
New Hampshire, USA             123
Arizona, USA                    88
Minnesota, USA                  81
United States                   63
Indiana, USA                    62
Tennessee, USA                  53
Mississippi, USA                51
Vermont, USA                    34
Nebraska, USA                   31
Missouri, USA                   22
Idaho, USA                      21
Nevada, USA                     18
Oklahoma, USA                   13
Utah, USA                       13
Kentucky, USA                    6
Montana, USA                     6
Kansas, USA                      5
Iowa, USA                        5
Arkansas, USA                    4
West Virginia, USA               2
Ontario, Canada                  2
Wyoming, USA                     1
South Dakota, USA                1
North Dakota, USA                1
New Mexico, USA                  1
Name: State, dtype: int64

In [18]:
#the number of times ocean cleanup done in each state
ocean["Zone"].value_counts()

Los Angeles County, CA, USA     2499
Palm Beach County, FL, USA      2217
San Diego County, CA, USA       1851
Pinellas County, FL, USA        1757
Miami-Dade County, FL, USA      1650
                                ...
Dawson County, GA, USA             1
Somerset County, PA, USA           1
Manassas Park, VA 20111, USA       1
Putnam County, WV, USA             1
Moore County, NC, USA              1
Name: Zone, Length: 900, dtype: int64

In [19]:
#the number of times ocean cleanup done in each month
ocean["Month"].value_counts()

9.0     16767
10.0     3854
7.0      2641
6.0      2617
4.0      2400
5.0      2152
8.0      1982
3.0      1452
11.0     1200
2.0      1078
1.0       979
12.0      771
Name: Month, dtype: int64

In [20]:
#the number of times ocean cleanup done on each weekday
ocean["Weekday"].value_counts()

5.0    19397
6.0     3738
4.0     3679
3.0     3000
2.0     2835
0.0     2707
1.0     2537
Name: Weekday, dtype: int64

In [32]:
#creating a new variable - landfill
ocean['Landfill'] = ocean['Cigarette Butts'] + ocean['Food Wrappers (candy, chips, etc.)']+ocean['Straws, Stirrers']
+ ocean['Forks, Knives, Spoons']+ocean['Beverage Bottles (Glass)']+ocean['Grocery Bags (Plastic)']+ocean['Cups, Plates (Plastic)']
+ ocean['Cups, Plates (Foam)']+ocean['Fishing Buoys, Pots & Traps']+ocean['Fishing Net & Pieces']+ocean['Fishing Line (1 yard/meter = 1 piece)']
+ ocean['Rope (1 yard/meter = 1 piece)']+ocean['Other Plastic/Foam Packaging']+ocean['Strapping Bands']+ocean['Tobacco Packaging/Wrap']
+ ocean['Other Packaging (Clean Swell)']+ocean['Balloons']+ocean['Cigarette Lighters']+ocean['Construction Materials']+ocean['Fireworks']
+ ocean['Other Trash (Clean Swell)']+ocean['Condoms']+ocean['Diapers']+ocean['Syringes']+ocean['Tampons/Tampon Applicators']
+ ocean['Personal Hygiene (Clean Swell)']+ocean['Foam Pieces']+ocean['Glass Pieces']+ocean['Plastic Pieces']

0              0
1              2
2              0
3              0
4              0
          ...
37899        881
37900        152
37901       1337
37902       1089
37903    6868908
Length: 37894, dtype: int64

In [33]:
ocean['Landfill']

0              1
1              1
2              1
3              2
4              2
          ...
37899        367
37900       1435
37901        782
37902       2582
37903    5098125
Name: Landfill, Length: 37894, dtype: int64

In [34]:
#creating a new variable - recycle
ocean['Recycle'] = ocean['Take Out/Away Containers (Plastic)']+ocean['Take Out/Away Containers (Foam)']+ocean['Bottle Caps (Plastic)']
+ocean['Bottle Caps (Metal)']+ocean['Lids (Plastic)']+ocean['Beverage Bottles (Plastic)']+ocean['Beverage Cans']+ocean['Other Plastic Bags']
+ocean['Fishing Gear (Clean Swell)']+ocean['6-Pack Holders']+ocean['Other Plastic Bottles (oil, bleach, etc.)']+ocean['Appliances (refrigerators, washers, etc.)']
+ocean['Tires']+ocean['Toys']

0            0
1            0
2            1
3            0
4            0
         ...
37899        0
37900        0
37901        0
37902        0
37903    88056
Length: 37894, dtype: int64

In [35]:
ocean['Recycle']

0              0
1              3
2              1
3             12
4             12
          ...
37899        242
37900        330
37901        541
37902         79
37903    1491694
Name: Recycle, Length: 37894, dtype: int64

In [36]:
#creating a new variable - compost
ocean['Compost']=ocean['Paper Bags']+ocean['Cups, Plates (Paper)']+ocean['Cigar Tips']

In [37]:
ocean['Compost']

0             0
1             1
2             0
3             0
4             0
          ...
37899        47
37900        35
37901       127
37902        40
37903    374727
Name: Compost, Length: 37894, dtype: int64

In [38]:
ocean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37894 entries, 0 to 37903
Data columns (total 68 columns):
Cleanup ID                                   37894 non-null object
Zone                                         37655 non-null object
State                                        37567 non-null object
Country                                      37893 non-null object
GPS                                          37893 non-null object
Cleanup Type                                 37893 non-null object
Cleanup Date                                 37893 non-null datetime64[ns]
Group Name                                   26631 non-null object
Adults                                       37893 non-null float64
Children                                     37893 non-null float64
People                                       37893 non-null float64
Pounds                                       37893 non-null float64
Miles                                        37893 non-null float64
# of bags                                    37893 non-null float64
Cigarette Butts                              37894 non-null int64
Food Wrappers (candy, chips, etc.)           37894 non-null int64
Take Out/Away Containers (Plastic)           37894 non-null int64
Take Out/Away Containers (Foam)              37894 non-null int64
Bottle Caps (Plastic)                        37894 non-null int64
Bottle Caps (Metal)                          37894 non-null int64
Lids (Plastic)                               37894 non-null int64
Straws, Stirrers                             37894 non-null int64
Forks, Knives, Spoons                        37894 non-null int64
Beverage Bottles (Plastic)                   37894 non-null int64
Beverage Bottles (Glass)                     37894 non-null int64
Beverage Cans                                37894 non-null int64
Grocery Bags (Plastic)                       37894 non-null int64
Other Plastic Bags                           37894 non-null int64
Paper Bags                                   37894 non-null int64
Cups, Plates (Paper)                         37894 non-null int64
Cups, Plates (Plastic)                       37894 non-null int64
Cups, Plates (Foam)                          37894 non-null int64
Fishing Buoys, Pots & Traps                  37894 non-null int64
Fishing Net & Pieces                         37894 non-null int64
Fishing Line (1 yard/meter = 1 piece)        37894 non-null int64
Rope (1 yard/meter = 1 piece)                37894 non-null int64
Fishing Gear (Clean Swell)                   37894 non-null int64
6-Pack Holders                               37894 non-null int64
Other Plastic/Foam Packaging                 37894 non-null int64
Other Plastic Bottles (oil, bleach, etc.)    37894 non-null int64
Strapping Bands                              37894 non-null int64
Tobacco Packaging/Wrap                       37894 non-null int64
Other Packaging (Clean Swell)                37894 non-null int64
Appliances (refrigerators, washers, etc.)    37894 non-null int64
Balloons                                     37894 non-null int64
Cigar Tips                                   37894 non-null int64
Cigarette Lighters                           37894 non-null int64
Construction Materials                       37894 non-null int64
Fireworks                                    37894 non-null int64
Tires                                        37894 non-null int64
Toys                                         37894 non-null int64
Other Trash (Clean Swell)                    37894 non-null int64
Condoms                                      37894 non-null int64
Diapers                                      37894 non-null int64
Syringes                                     37894 non-null int64
Tampons/Tampon Applicators                   37894 non-null int64
Personal Hygiene (Clean Swell)               37894 non-null int64
Foam Pieces                                  37894 non-null int64
Glass Pieces                                 37894 non-null int64
Plastic Pieces                               37894 non-null int64
Total Items Collected                        37893 non-null float64
Year                                         37893 non-null float64
Month                                        37893 non-null float64
Weekday                                      37893 non-null float64
Day                                          37893 non-null float64
Landfill                                     37894 non-null int64
Recycle                                      37894 non-null int64
Compost                                      37894 non-null int64
dtypes: datetime64[ns](1), float64(11), int64(49), object(7)
memory usage: 19.9+ MB

In [39]:
#def season(c):
    if (ocean['Month'] >= 3 & ocean['Day'] >= 1) & (ocean['Month'] <= 5 & ocean['Day'] <= 31):
        return 'Spring'
    elif (ocean['Month'] >= 6 & ocean['Day'] >= 1) & (ocean['Month'] <= 8 & ocean['Day'] <= 31):
        return 'Summer'
    elif (ocean['Month'] >= 9 & ocean['Day'] >= 1) & (ocean['Month'] <= 11 & ocean['Day'] <= 30):
        return 'Fall'
    else:
        return 'Winter'

In [44]:
#ocean.apply (lambda c: season(c), axis=1)
#ocean['Season'] = ocean.apply(season)

In [45]:
#ocean['Season']

In [43]:
ocean['Month'].value_counts()

9.0     16767
10.0     3854
7.0      2641
6.0      2617
4.0      2400
5.0      2152
8.0      1982
3.0      1452
11.0     1200
2.0      1078
1.0       979
12.0      771
Name: Month, dtype: int64

In [47]:
#def season_of_date(a):
    year = str(Date.Year)
    seasons = {'Spring': pd.date_range(start='21/03/'+year, end='20/06/'+year),
               'Summer': pd.date_range(start='21/06/'+year, end='22/09/'+year),
               'Fall': pd.date_range(start='23/09/'+year, end='20/12/'+year)}
    if date in seasons['Spring']:
        return 'Spring'
    if date in seasons['Summer']:
        return 'Summer'
    if date in seasons['Autumn']:
        return 'Fall'
    else:
        return 'Winter'

# Assuming df has a date column of type `datetime`
#ocean['Season'] = ocean['Cleanup Date'].map(season_of_date)

IndentationError: unexpected indent (<ipython-input-47-be84e10d6bb5>, line 3)