In [82]:
import pandas as pd
import datetime

In [83]:
#load the file
ocean = pd.read_csv('dataset/Level5_BAH_OceanCleanup/Data_Level5_BAH_OceanCleanup.csv', low_memory=False, encoding='utf-8')

In [84]:
#top 10 rows of the dataset
ocean.head()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Other Trash (Clean Swell),Condoms,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected
0,86,"Cuyahoga County, OH, USA","Ohio, USA",United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",12/22/2014,NaN,1.0,0.0,...,0,0,0,0,0,0,0,0,0,3.0
1,87,"Fairfax County, VA, USA","Virginia, USA",United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",12/24/2014,NaN,1.0,0.0,...,0,0,0,0,0,0,0,0,2,10.0
2,92,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.04405","Land (beach, shoreline and inland)",2/19/2015,NaN,1.0,0.0,...,1,0,0,0,0,0,0,0,0,4.0
3,93,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2/19/2015,NaN,1.0,0.0,...,0,0,0,0,0,0,0,0,0,14.0
4,94,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2/19/2015,NaN,1.0,0.0,...,0,0,0,0,0,0,0,0,0,14.0

In [85]:
#bottom ten rows of the dataset
ocean.tail()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Other Trash (Clean Swell),Condoms,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected
37899,96515,"Broward County, FL, USA","Florida, USA",United States,"26.192071595116, -80.095065761509","Land (beach, shoreline and inland)",9/21/2019,Lauderdale By The Sea at El Prado Park,173.0,0.0,...,0,2,2,2,4,0,194,35,652,1830.0
37900,96516,"Broward County, FL, USA","Florida, USA",United States,"26.167607025494, -80.098590082316","Land (beach, shoreline and inland)",9/21/2019,Fort Lauderdale at Earl Lifshey Park,79.0,0.0,...,0,26,2,0,4,0,80,12,60,2370.0
37901,96517,"Broward County, FL, USA","Florida, USA",United States,"26.141126021262, -80.103590059501","Land (beach, shoreline and inland)",9/21/2019,Hugh Taylor Birch State Park,135.0,0.0,...,0,15,6,5,23,0,141,25,1171,3788.0
37902,96518,"Humboldt County, CA, USA","California, USA",United States,"40.809835251824, -124.14836608941","Land (beach, shoreline and inland)",9/21/2019,Caltrans- ZWCCD 2019,16.0,4.0,...,0,6,2,22,3,0,65,92,932,4205.0
37903,Totals:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,352468,15327,14429,11342,25685,40516,3292299,542969,2993124,NaN

In [86]:
#get the number of rows and columns
ocean.shape

(37904, 61)

In [87]:
#descriptive statistics
ocean.describe()

,Adults,Children,People,Pounds,Miles,# of bags,Cigarette Butts,"Food Wrappers (candy, chips, etc.)",Take Out/Away Containers (Plastic),Take Out/Away Containers (Foam),...,Other Trash (Clean Swell),Condoms,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected
count,37903.000000,37903.000000,37903.000000,37903.000000,37903.000000,37903.000000,3.790400e+04,3.790400e+04,37904.000000,37904.000000,...,37904.000000,37904.000000,37904.000000,37904.000000,37904.000000,37904.000000,3.790400e+04,37904.000000,3.790400e+04,37903.000000
mean,16.621481,2.452814,19.074295,310.799010,1.426367,7.360103,1.749690e+02,6.619354e+01,11.831838,8.680614,...,18.597932,0.808727,0.761344,0.598459,1.355266,2.137822,1.737178e+02,28.649694,1.579318e+02,502.647284
std,200.761902,18.684501,203.218661,4621.795387,15.329109,157.094929,1.704443e+04,6.445898e+03,1153.418164,846.008907,...,1810.697419,78.887605,74.457778,58.585591,132.347617,208.136822,1.719248e+04,2792.134959,1.539350e+04,4060.754999
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,1.000000,0.000000,1.000000,1.450000,0.027500,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,19.000000
50%,2.000000,0.000000,2.000000,5.600000,0.341700,0.000000,4.000000e+00,5.000000e+00,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,8.000000e+00,84.000000
75%,6.000000,0.000000,7.000000,24.000000,1.105100,0.000000,3.000000e+01,1.900000e+01,3.000000,2.000000,...,8.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000,4.300000e+01,264.000000
max,22060.000000,1291.000000,22060.000000,425025.000000,2423.166700,18581.000000,3.316012e+06,1.254500e+06,224237.000000,164515.000000,...,352468.000000,15327.000000,14429.000000,11342.000000,25685.000000,40516.000000,3.292299e+06,542969.000000,2.993124e+06,440496.000000

In [88]:
#get the variable names
ocean.columns

Index(['Cleanup ID', 'Zone', 'State', 'Country', 'GPS', 'Cleanup Type',
       'Cleanup Date', 'Group Name', 'Adults', 'Children', 'People', 'Pounds',
       'Miles', '# of bags', 'Cigarette Butts',
       'Food Wrappers (candy, chips, etc.)',
       'Take Out/Away Containers (Plastic)', 'Take Out/Away Containers (Foam)',
       'Bottle Caps (Plastic)', 'Bottle Caps (Metal)', 'Lids (Plastic)',
       'Straws, Stirrers', 'Forks, Knives, Spoons',
       'Beverage Bottles (Plastic)', 'Beverage Bottles (Glass)',
       'Beverage Cans', 'Grocery Bags (Plastic)', 'Other Plastic Bags',
       'Paper Bags', 'Cups, Plates (Paper)', 'Cups, Plates (Plastic)',
       'Cups, Plates (Foam)', 'Fishing Buoys, Pots & Traps',
       'Fishing Net & Pieces', 'Fishing Line (1 yard/meter = 1 piece)',
       'Rope (1 yard/meter = 1 piece)', 'Fishing Gear (Clean Swell)',
       '6-Pack Holders', 'Other Plastic/Foam Packaging',
       'Other Plastic Bottles (oil, bleach, etc.)', 'Strapping Bands',
       'Tobacco Packaging/Wrap', 'Other Packaging (Clean Swell)',
       'Appliances (refrigerators, washers, etc.)', 'Balloons', 'Cigar Tips',
       'Cigarette Lighters', 'Construction Materials', 'Fireworks', 'Tires',
       'Toys', 'Other Trash (Clean Swell)', 'Condoms', 'Diapers', 'Syringes',
       'Tampons/Tampon Applicators', 'Personal Hygiene (Clean Swell)',
       'Foam Pieces', 'Glass Pieces', 'Plastic Pieces',
       'Total Items Collected'],
      dtype='object')

In [89]:
#get the number of observations for each variable
ocean.count()

Cleanup ID                                   37904
Zone                                         37665
State                                        37577
Country                                      37903
GPS                                          37903
Cleanup Type                                 37903
Cleanup Date                                 37903
Group Name                                   26636
Adults                                       37903
Children                                     37903
People                                       37903
Pounds                                       37903
Miles                                        37903
# of bags                                    37903
Cigarette Butts                              37904
Food Wrappers (candy, chips, etc.)           37904
Take Out/Away Containers (Plastic)           37904
Take Out/Away Containers (Foam)              37904
Bottle Caps (Plastic)                        37904
Bottle Caps (Metal)                          37904
Lids (Plastic)                               37904
Straws, Stirrers                             37904
Forks, Knives, Spoons                        37904
Beverage Bottles (Plastic)                   37904
Beverage Bottles (Glass)                     37904
Beverage Cans                                37904
Grocery Bags (Plastic)                       37904
Other Plastic Bags                           37904
Paper Bags                                   37904
Cups, Plates (Paper)                         37904
                                             ...
Cups, Plates (Foam)                          37904
Fishing Buoys, Pots & Traps                  37904
Fishing Net & Pieces                         37904
Fishing Line (1 yard/meter = 1 piece)        37904
Rope (1 yard/meter = 1 piece)                37904
Fishing Gear (Clean Swell)                   37904
6-Pack Holders                               37904
Other Plastic/Foam Packaging                 37904
Other Plastic Bottles (oil, bleach, etc.)    37904
Strapping Bands                              37904
Tobacco Packaging/Wrap                       37904
Other Packaging (Clean Swell)                37904
Appliances (refrigerators, washers, etc.)    37904
Balloons                                     37904
Cigar Tips                                   37904
Cigarette Lighters                           37904
Construction Materials                       37904
Fireworks                                    37904
Tires                                        37904
Toys                                         37904
Other Trash (Clean Swell)                    37904
Condoms                                      37904
Diapers                                      37904
Syringes                                     37904
Tampons/Tampon Applicators                   37904
Personal Hygiene (Clean Swell)               37904
Foam Pieces                                  37904
Glass Pieces                                 37904
Plastic Pieces                               37904
Total Items Collected                        37903
Length: 61, dtype: int64

In [94]:
#finding the percentage of missing values
missing_rows = ocean.isnull().sum()/ocean.shape[0]
missing_rows

Cleanup ID                                   0.000000
Zone                                         0.006307
State                                        0.008629
Country                                      0.000026
GPS                                          0.000026
Cleanup Type                                 0.000026
Cleanup Date                                 0.000026
Group Name                                   0.297224
Adults                                       0.000026
Children                                     0.000026
People                                       0.000026
Pounds                                       0.000026
Miles                                        0.000026
# of bags                                    0.000026
Cigarette Butts                              0.000000
Food Wrappers (candy, chips, etc.)           0.000000
Take Out/Away Containers (Plastic)           0.000000
Take Out/Away Containers (Foam)              0.000000
Bottle Caps (Plastic)                        0.000000
Bottle Caps (Metal)                          0.000000
Lids (Plastic)                               0.000000
Straws, Stirrers                             0.000000
Forks, Knives, Spoons                        0.000000
Beverage Bottles (Plastic)                   0.000000
Beverage Bottles (Glass)                     0.000000
Beverage Cans                                0.000000
Grocery Bags (Plastic)                       0.000000
Other Plastic Bags                           0.000000
Paper Bags                                   0.000000
Cups, Plates (Paper)                         0.000000
                                               ...
Fishing Buoys, Pots & Traps                  0.000000
Fishing Net & Pieces                         0.000000
Fishing Line (1 yard/meter = 1 piece)        0.000000
Rope (1 yard/meter = 1 piece)                0.000000
Fishing Gear (Clean Swell)                   0.000000
6-Pack Holders                               0.000000
Other Plastic/Foam Packaging                 0.000000
Other Plastic Bottles (oil, bleach, etc.)    0.000000
Strapping Bands                              0.000000
Tobacco Packaging/Wrap                       0.000000
Other Packaging (Clean Swell)                0.000000
Appliances (refrigerators, washers, etc.)    0.000000
Balloons                                     0.000000
Cigar Tips                                   0.000000
Cigarette Lighters                           0.000000
Construction Materials                       0.000000
Fireworks                                    0.000000
Tires                                        0.000000
Toys                                         0.000000
Other Trash (Clean Swell)                    0.000000
Condoms                                      0.000000
Diapers                                      0.000000
Syringes                                     0.000000
Tampons/Tampon Applicators                   0.000000
Personal Hygiene (Clean Swell)               0.000000
Foam Pieces                                  0.000000
Glass Pieces                                 0.000000
Plastic Pieces                               0.000000
Total Items Collected                        0.000026
Year                                         0.000026
Length: 62, dtype: float64

In [95]:
ocean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37894 entries, 0 to 37903
Data columns (total 62 columns):
Cleanup ID                                   37894 non-null object
Zone                                         37655 non-null object
State                                        37567 non-null object
Country                                      37893 non-null object
GPS                                          37893 non-null object
Cleanup Type                                 37893 non-null object
Cleanup Date                                 37893 non-null datetime64[ns]
Group Name                                   26631 non-null object
Adults                                       37893 non-null float64
Children                                     37893 non-null float64
People                                       37893 non-null float64
Pounds                                       37893 non-null float64
Miles                                        37893 non-null float64
# of bags                                    37893 non-null float64
Cigarette Butts                              37894 non-null int64
Food Wrappers (candy, chips, etc.)           37894 non-null int64
Take Out/Away Containers (Plastic)           37894 non-null int64
Take Out/Away Containers (Foam)              37894 non-null int64
Bottle Caps (Plastic)                        37894 non-null int64
Bottle Caps (Metal)                          37894 non-null int64
Lids (Plastic)                               37894 non-null int64
Straws, Stirrers                             37894 non-null int64
Forks, Knives, Spoons                        37894 non-null int64
Beverage Bottles (Plastic)                   37894 non-null int64
Beverage Bottles (Glass)                     37894 non-null int64
Beverage Cans                                37894 non-null int64
Grocery Bags (Plastic)                       37894 non-null int64
Other Plastic Bags                           37894 non-null int64
Paper Bags                                   37894 non-null int64
Cups, Plates (Paper)                         37894 non-null int64
Cups, Plates (Plastic)                       37894 non-null int64
Cups, Plates (Foam)                          37894 non-null int64
Fishing Buoys, Pots & Traps                  37894 non-null int64
Fishing Net & Pieces                         37894 non-null int64
Fishing Line (1 yard/meter = 1 piece)        37894 non-null int64
Rope (1 yard/meter = 1 piece)                37894 non-null int64
Fishing Gear (Clean Swell)                   37894 non-null int64
6-Pack Holders                               37894 non-null int64
Other Plastic/Foam Packaging                 37894 non-null int64
Other Plastic Bottles (oil, bleach, etc.)    37894 non-null int64
Strapping Bands                              37894 non-null int64
Tobacco Packaging/Wrap                       37894 non-null int64
Other Packaging (Clean Swell)                37894 non-null int64
Appliances (refrigerators, washers, etc.)    37894 non-null int64
Balloons                                     37894 non-null int64
Cigar Tips                                   37894 non-null int64
Cigarette Lighters                           37894 non-null int64
Construction Materials                       37894 non-null int64
Fireworks                                    37894 non-null int64
Tires                                        37894 non-null int64
Toys                                         37894 non-null int64
Other Trash (Clean Swell)                    37894 non-null int64
Condoms                                      37894 non-null int64
Diapers                                      37894 non-null int64
Syringes                                     37894 non-null int64
Tampons/Tampon Applicators                   37894 non-null int64
Personal Hygiene (Clean Swell)               37894 non-null int64
Foam Pieces                                  37894 non-null int64
Glass Pieces                                 37894 non-null int64
Plastic Pieces                               37894 non-null int64
Total Items Collected                        37893 non-null float64
Year                                         37893 non-null float64
dtypes: datetime64[ns](1), float64(8), int64(46), object(7)
memory usage: 18.2+ MB

In [97]:
# drop the rows which has year more than 2020
ocean.drop(ocean[ocean['Cleanup Date'] == '0218-04-20'].index, inplace=True)
ocean['Cleanup Date'] = pd.to_datetime(ocean['Cleanup Date'])
ocean['Year'] = pd.DatetimeIndex(ocean['Cleanup Date']).year
ocean.drop(ocean[ocean['Year'] > 2020].index, inplace=True)

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 218-04-20 00:00:00

In [98]:
ocean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37894 entries, 0 to 37903
Data columns (total 62 columns):
Cleanup ID                                   37894 non-null object
Zone                                         37655 non-null object
State                                        37567 non-null object
Country                                      37893 non-null object
GPS                                          37893 non-null object
Cleanup Type                                 37893 non-null object
Cleanup Date                                 37893 non-null datetime64[ns]
Group Name                                   26631 non-null object
Adults                                       37893 non-null float64
Children                                     37893 non-null float64
People                                       37893 non-null float64
Pounds                                       37893 non-null float64
Miles                                        37893 non-null float64
# of bags                                    37893 non-null float64
Cigarette Butts                              37894 non-null int64
Food Wrappers (candy, chips, etc.)           37894 non-null int64
Take Out/Away Containers (Plastic)           37894 non-null int64
Take Out/Away Containers (Foam)              37894 non-null int64
Bottle Caps (Plastic)                        37894 non-null int64
Bottle Caps (Metal)                          37894 non-null int64
Lids (Plastic)                               37894 non-null int64
Straws, Stirrers                             37894 non-null int64
Forks, Knives, Spoons                        37894 non-null int64
Beverage Bottles (Plastic)                   37894 non-null int64
Beverage Bottles (Glass)                     37894 non-null int64
Beverage Cans                                37894 non-null int64
Grocery Bags (Plastic)                       37894 non-null int64
Other Plastic Bags                           37894 non-null int64
Paper Bags                                   37894 non-null int64
Cups, Plates (Paper)                         37894 non-null int64
Cups, Plates (Plastic)                       37894 non-null int64
Cups, Plates (Foam)                          37894 non-null int64
Fishing Buoys, Pots & Traps                  37894 non-null int64
Fishing Net & Pieces                         37894 non-null int64
Fishing Line (1 yard/meter = 1 piece)        37894 non-null int64
Rope (1 yard/meter = 1 piece)                37894 non-null int64
Fishing Gear (Clean Swell)                   37894 non-null int64
6-Pack Holders                               37894 non-null int64
Other Plastic/Foam Packaging                 37894 non-null int64
Other Plastic Bottles (oil, bleach, etc.)    37894 non-null int64
Strapping Bands                              37894 non-null int64
Tobacco Packaging/Wrap                       37894 non-null int64
Other Packaging (Clean Swell)                37894 non-null int64
Appliances (refrigerators, washers, etc.)    37894 non-null int64
Balloons                                     37894 non-null int64
Cigar Tips                                   37894 non-null int64
Cigarette Lighters                           37894 non-null int64
Construction Materials                       37894 non-null int64
Fireworks                                    37894 non-null int64
Tires                                        37894 non-null int64
Toys                                         37894 non-null int64
Other Trash (Clean Swell)                    37894 non-null int64
Condoms                                      37894 non-null int64
Diapers                                      37894 non-null int64
Syringes                                     37894 non-null int64
Tampons/Tampon Applicators                   37894 non-null int64
Personal Hygiene (Clean Swell)               37894 non-null int64
Foam Pieces                                  37894 non-null int64
Glass Pieces                                 37894 non-null int64
Plastic Pieces                               37894 non-null int64
Total Items Collected                        37893 non-null float64
Year                                         37893 non-null float64
dtypes: datetime64[ns](1), float64(8), int64(46), object(7)
memory usage: 18.2+ MB

In [99]:
# creating month, year, weekday
ocean['Month'] = pd.DatetimeIndex(ocean['Cleanup Date']).month
ocean['Weekday'] = pd.DatetimeIndex(ocean['Cleanup Date']).weekday
ocean['Day'] = pd.DatetimeIndex(ocean['Cleanup Date']).day

In [100]:
ocean.head()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Year,Month,Weekday,Day
0,86,"Cuyahoga County, OH, USA","Ohio, USA",United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",2014-12-22,NaN,1.0,0.0,...,0,0,0,0,0,3.0,2014.0,12.0,0.0,22.0
1,87,"Fairfax County, VA, USA","Virginia, USA",United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",2014-12-24,NaN,1.0,0.0,...,0,0,0,0,2,10.0,2014.0,12.0,2.0,24.0
2,92,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.04405","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,4.0,2015.0,2.0,3.0,19.0
3,93,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,14.0,2015.0,2.0,3.0,19.0
4,94,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,14.0,2015.0,2.0,3.0,19.0

In [101]:
#most frequently done cleanup type
ocean["Cleanup Type"].value_counts()

Land (beach, shoreline and inland)                  37106
Watercraft (powerboat, sailboat, kayak or canoe)      571
Underwater                                            216
Name: Cleanup Type, dtype: int64

In [102]:
#the number of times ocean cleanup done in each state
ocean["State"].value_counts()

Florida, USA                 11317
California, USA               9268
North Carolina, USA           1798
Washington, USA               1233
New York, USA                 1179
South Carolina, USA           1168
Texas, USA                    1070
Virginia, USA                 1068
Oregon, USA                    936
Hawaii, USA                    749
Massachusetts, USA             616
Pennsylvania, USA              596
Ohio, USA                      499
Rhode Island, USA              499
Illinois, USA                  482
New Jersey, USA                470
Maryland, USA                  467
Michigan, USA                  442
Connecticut, USA               407
Maine, USA                     398
District of Columbia, USA      371
Louisiana, USA                 363
Georgia, USA                   345
Delaware, USA                  331
Wisconsin, USA                 296
Alabama, USA                   197
Alaska, USA                    163
Colorado, USA                  132
New Hampshire, USA             123
Arizona, USA                    88
Minnesota, USA                  81
United States                   63
Indiana, USA                    62
Tennessee, USA                  53
Mississippi, USA                51
Vermont, USA                    34
Nebraska, USA                   31
Missouri, USA                   22
Idaho, USA                      21
Nevada, USA                     18
Utah, USA                       13
Oklahoma, USA                   13
Montana, USA                     6
Kentucky, USA                    6
Kansas, USA                      5
Iowa, USA                        5
Arkansas, USA                    4
West Virginia, USA               2
Ontario, Canada                  2
North Dakota, USA                1
New Mexico, USA                  1
Wyoming, USA                     1
South Dakota, USA                1
Name: State, dtype: int64

In [103]:
#the number of times ocean cleanup done in each state
ocean["Zone"].value_counts()

Los Angeles County, CA, USA                     2499
Palm Beach County, FL, USA                      2217
San Diego County, CA, USA                       1851
Pinellas County, FL, USA                        1757
Miami-Dade County, FL, USA                      1650
Hillsborough County, FL, USA                     940
Broward County, FL, USA                          815
Orange County, CA, USA                           792
King County, WA, USA                             698
Colleton County, SC, USA                         501
Carteret County, NC, USA                         496
Indian River County, FL, USA                     475
Alameda County, CA, USA                          446
Dare County, NC, USA                             433
Monterey County, CA, USA                         431
Maui County, HI, USA                             429
St Johns County, FL, USA                         406
Duval County, FL, USA                            373
Washington, DC, USA                              370
San Francisco County, San Francisco, CA, USA     351
Suffolk County, NY, USA                          349
Martin County, FL, USA                           344
San Luis Obispo County, CA, USA                  339
Santa Cruz County, CA, USA                       318
Brevard County, FL, USA                          312
Cook County, IL, USA                             295
Santa Barbara County, CA, USA                    278
Sussex County, DE, USA                           275
Marin County, CA, USA                            270
New Hanover County, NC, USA                      264
                                                ...
El Paso County, TX, USA                            1
Southeast Fairbanks, AK, USA                       1
Lincoln County, SD, USA                            1
Butts County, GA, USA                              1
Colquitt County, GA, USA                           1
Nome, AK, USA                                      1
Page County, VA, USA                               1
Douglas County, GA, USA                            1
Whitfield County, GA, USA                          1
Montgomery County, NY, USA                         1
Waukesha County, WI, USA                           1
Manassas Park, VA 20111, USA                       1
Wheeler County, OR, USA                            1
St Charles County, MO, USA                         1
Hinds County, MS, USA                              1
La Crosse County, WI, USA                          1
Baker County, GA, USA                              1
Washington County, VT, USA                         1
Pierce County, GA, USA                             1
Adams County, CO, USA                              1
Wilkinson County, GA, USA                          1
Warren County, NJ, USA                             1
San Clemente, CA, USA                              1
Marion County, SC, USA                             1
Rock County, WI, USA                               1
Wayne County, GA, USA                              1
Bryan County, GA, USA                              1
Norton County, KS, USA                             1
Howard County, TX, USA                             1
Bastrop County, TX, USA                            1
Name: Zone, Length: 900, dtype: int64

In [104]:
#the number of times ocean cleanup done in each month
ocean["Month"].value_counts()

9.0     16767
10.0     3854
7.0      2641
6.0      2617
4.0      2400
5.0      2152
8.0      1982
3.0      1452
11.0     1200
2.0      1078
1.0       979
12.0      771
Name: Month, dtype: int64

In [105]:
#the number of times ocean cleanup done on each weekday
ocean["Weekday"].value_counts()

5.0    19397
6.0     3738
4.0     3679
3.0     3000
2.0     2835
0.0     2707
1.0     2537
Name: Weekday, dtype: int64

In [106]:
#creating a new variable - landfill
ocean['Landfill'] = ocean['Cigarette Butts'] + ocean['Food Wrappers (candy, chips, etc.)']+ocean['Straws, Stirrers']
+ ocean['Forks, Knives, Spoons']+ocean['Beverage Bottles (Glass)']+ocean['Grocery Bags (Plastic)']+ocean['Cups, Plates (Plastic)']
+ ocean['Cups, Plates (Foam)']+ocean['Fishing Buoys, Pots & Traps']+ocean['Fishing Net & Pieces']+ocean['Fishing Line (1 yard/meter = 1 piece)']
+ ocean['Rope (1 yard/meter = 1 piece)']+ocean['Other Plastic/Foam Packaging']+ocean['Strapping Bands']+ocean['Tobacco Packaging/Wrap']
+ ocean['Other Packaging (Clean Swell)']+ocean['Balloons']+ocean['Cigarette Lighters']+ocean['Construction Materials']+ocean['Fireworks']
+ ocean['Other Trash (Clean Swell)']+ocean['Condoms']+ocean['Diapers']+ocean['Syringes']+ocean['Tampons/Tampon Applicators']
+ ocean['Personal Hygiene (Clean Swell)']+ocean['Foam Pieces']+ocean['Glass Pieces']+ocean['Plastic Pieces']

0              0
1              2
2              0
3              0
4              0
5              2
6              1
7              0
8              2
9              1
10             0
11             0
12             1
13             0
14             1
15             0
16             0
17             0
18             0
19             1
20             1
21             0
22             0
23             0
24             0
25             0
26             0
27             1
28             2
29             1
          ...
37874         93
37875        233
37876        230
37877        112
37878         58
37879         42
37880        187
37881         29
37882          0
37883          5
37884          3
37885         53
37886        165
37887         58
37888        555
37889         18
37890         31
37891         97
37892        369
37893          1
37894       7020
37895          0
37896         99
37897        355
37898       4106
37899        881
37900        152
37901       1337
37902       1089
37903    6868908
Length: 37894, dtype: int64

In [107]:
ocean['Landfill']

0              1
1              1
2              1
3              2
4              2
5              1
6              2
7              2
8              3
9              1
10             7
11             1
12             0
13             0
14             1
15             1
16             1
17             0
18             1
19             1
20             1
21             0
22             1
23             0
24             9
25             1
26             3
27             4
28             5
29             0
          ...
37874        164
37875        239
37876        160
37877         26
37878        262
37879          7
37880        130
37881         50
37882          0
37883         58
37884          9
37885        526
37886        106
37887        263
37888        933
37889         39
37890         36
37891        354
37892        440
37893         27
37894       2706
37895        411
37896        223
37897        118
37898       2216
37899        367
37900       1435
37901        782
37902       2582
37903    5098125
Name: Landfill, Length: 37894, dtype: int64

In [108]:
#creating a new variable - recycle
ocean['Recycle'] = ocean['Take Out/Away Containers (Plastic)']+ocean['Take Out/Away Containers (Foam)']+ocean['Bottle Caps (Plastic)']
+ocean['Bottle Caps (Metal)']+ocean['Lids (Plastic)']+ocean['Beverage Bottles (Plastic)']+ocean['Beverage Cans']+ocean['Other Plastic Bags']
+ocean['Fishing Gear (Clean Swell)']+ocean['6-Pack Holders']+ocean['Other Plastic Bottles (oil, bleach, etc.)']+ocean['Appliances (refrigerators, washers, etc.)']
+ocean['Tires']+ocean['Toys']

0            0
1            0
2            1
3            0
4            0
5            1
6            0
7            0
8            0
9            0
10           0
11           0
12           0
13           0
14           0
15           0
16           0
17           0
18           0
19           0
20           0
21           0
22           0
23           0
24           0
25           0
26           6
27           0
28           1
29           0
         ...
37874        0
37875        0
37876        2
37877        3
37878        0
37879        0
37880       10
37881        1
37882        0
37883        0
37884        0
37885        0
37886        7
37887        1
37888        1
37889        0
37890        0
37891        0
37892        0
37893        1
37894        0
37895        0
37896        0
37897        5
37898        9
37899        0
37900        0
37901        0
37902        0
37903    88056
Length: 37894, dtype: int64

In [109]:
ocean['Recycle']

0              0
1              3
2              1
3             12
4             12
5              3
6              0
7              2
8              0
9              1
10             0
11             2
12             1
13             1
14             2
15             0
16             1
17             2
18             2
19             2
20             0
21             1
22             1
23             3
24             0
25             2
26             5
27             5
28             7
29             0
          ...
37874         19
37875        110
37876         73
37877         78
37878         58
37879         25
37880         10
37881         14
37882         23
37883          8
37884          0
37885         79
37886        107
37887          9
37888        181
37889         13
37890          7
37891         15
37892        181
37893          7
37894       2226
37895        632
37896         37
37897        225
37898        853
37899        242
37900        330
37901        541
37902         79
37903    1491694
Name: Recycle, Length: 37894, dtype: int64

In [110]:
#creating a new variable - compost
ocean['Compost']=ocean['Paper Bags']+ocean['Cups, Plates (Paper)']+ocean['Cigar Tips']

In [111]:
ocean['Compost']

0             0
1             1
2             0
3             0
4             0
5             0
6             0
7             0
8             1
9             0
10            0
11            1
12            0
13            0
14            0
15            0
16            0
17            0
18            0
19            0
20            0
21            0
22            1
23            0
24            0
25            0
26            1
27            1
28            0
29            0
          ...
37874        41
37875        76
37876        27
37877         6
37878         8
37879         4
37880        13
37881         7
37882         0
37883         7
37884         9
37885         6
37886         4
37887        11
37888       138
37889         6
37890         0
37891         8
37892        71
37893         1
37894       444
37895        38
37896         1
37897        48
37898       234
37899        47
37900        35
37901       127
37902        40
37903    374727
Name: Compost, Length: 37894, dtype: int64

In [112]:
ocean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37894 entries, 0 to 37903
Data columns (total 68 columns):
Cleanup ID                                   37894 non-null object
Zone                                         37655 non-null object
State                                        37567 non-null object
Country                                      37893 non-null object
GPS                                          37893 non-null object
Cleanup Type                                 37893 non-null object
Cleanup Date                                 37893 non-null datetime64[ns]
Group Name                                   26631 non-null object
Adults                                       37893 non-null float64
Children                                     37893 non-null float64
People                                       37893 non-null float64
Pounds                                       37893 non-null float64
Miles                                        37893 non-null float64
# of bags                                    37893 non-null float64
Cigarette Butts                              37894 non-null int64
Food Wrappers (candy, chips, etc.)           37894 non-null int64
Take Out/Away Containers (Plastic)           37894 non-null int64
Take Out/Away Containers (Foam)              37894 non-null int64
Bottle Caps (Plastic)                        37894 non-null int64
Bottle Caps (Metal)                          37894 non-null int64
Lids (Plastic)                               37894 non-null int64
Straws, Stirrers                             37894 non-null int64
Forks, Knives, Spoons                        37894 non-null int64
Beverage Bottles (Plastic)                   37894 non-null int64
Beverage Bottles (Glass)                     37894 non-null int64
Beverage Cans                                37894 non-null int64
Grocery Bags (Plastic)                       37894 non-null int64
Other Plastic Bags                           37894 non-null int64
Paper Bags                                   37894 non-null int64
Cups, Plates (Paper)                         37894 non-null int64
Cups, Plates (Plastic)                       37894 non-null int64
Cups, Plates (Foam)                          37894 non-null int64
Fishing Buoys, Pots & Traps                  37894 non-null int64
Fishing Net & Pieces                         37894 non-null int64
Fishing Line (1 yard/meter = 1 piece)        37894 non-null int64
Rope (1 yard/meter = 1 piece)                37894 non-null int64
Fishing Gear (Clean Swell)                   37894 non-null int64
6-Pack Holders                               37894 non-null int64
Other Plastic/Foam Packaging                 37894 non-null int64
Other Plastic Bottles (oil, bleach, etc.)    37894 non-null int64
Strapping Bands                              37894 non-null int64
Tobacco Packaging/Wrap                       37894 non-null int64
Other Packaging (Clean Swell)                37894 non-null int64
Appliances (refrigerators, washers, etc.)    37894 non-null int64
Balloons                                     37894 non-null int64
Cigar Tips                                   37894 non-null int64
Cigarette Lighters                           37894 non-null int64
Construction Materials                       37894 non-null int64
Fireworks                                    37894 non-null int64
Tires                                        37894 non-null int64
Toys                                         37894 non-null int64
Other Trash (Clean Swell)                    37894 non-null int64
Condoms                                      37894 non-null int64
Diapers                                      37894 non-null int64
Syringes                                     37894 non-null int64
Tampons/Tampon Applicators                   37894 non-null int64
Personal Hygiene (Clean Swell)               37894 non-null int64
Foam Pieces                                  37894 non-null int64
Glass Pieces                                 37894 non-null int64
Plastic Pieces                               37894 non-null int64
Total Items Collected                        37893 non-null float64
Year                                         37893 non-null float64
Month                                        37893 non-null float64
Weekday                                      37893 non-null float64
Day                                          37893 non-null float64
Landfill                                     37894 non-null int64
Recycle                                      37894 non-null int64
Compost                                      37894 non-null int64
dtypes: datetime64[ns](1), float64(11), int64(49), object(7)
memory usage: 19.9+ MB

In [113]:
ocean['Month'].value_counts()

9.0     16767
10.0     3854
7.0      2641
6.0      2617
4.0      2400
5.0      2152
8.0      1982
3.0      1452
11.0     1200
2.0      1078
1.0       979
12.0      771
Name: Month, dtype: int64

In [114]:
ocean.head()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Glass Pieces,Plastic Pieces,Total Items Collected,Year,Month,Weekday,Day,Landfill,Recycle,Compost
0,86,"Cuyahoga County, OH, USA","Ohio, USA",United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",2014-12-22,NaN,1.0,0.0,...,0,0,3.0,2014.0,12.0,0.0,22.0,1,0,0
1,87,"Fairfax County, VA, USA","Virginia, USA",United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",2014-12-24,NaN,1.0,0.0,...,0,2,10.0,2014.0,12.0,2.0,24.0,1,3,1
2,92,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.04405","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,4.0,2015.0,2.0,3.0,19.0,1,1,0
3,93,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,14.0,2015.0,2.0,3.0,19.0,2,12,0
4,94,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,14.0,2015.0,2.0,3.0,19.0,2,12,0

In [115]:
ocean['State'] = ocean['State'].str.replace(', USA', '')
ocean.head()
ocean.shape

(37894, 68)

In [116]:
west = ["Alaska", "Arizona", "California", "Hawaii", "Idaho","Montana","Nevada","Oregon","Utah","Washington", "Wisconsin", "Wyoming"]
midwest = ["North Dakota","Illinois", "Indiana", "Iowa", "Kansas","Michigan","Minnesota","Nebraska","New Mexico","Ohio","South Dakota"]
northeast = ["Connecticut","Maine","Massachusetts","Missouri","New Hampshire","New Jersey","New York", "Pennsylvania", "Rhode Island","Vermont"]
south = ["South Carolina","Alabama","Arkansas", "Delaware","District of Columbia","Florida", "Georgia", "Kentucky", "Louisiana","Maryland","Mississippi","Oklahoma","South Carolina","Tennessee", "Texas","West Virginia","Virginia"]

In [117]:
for i, row in ocean.iterrows():
    if row['State'] in west: 
        ocean.loc[i,'Region'] = 'West'
    elif row['State'] in midwest:
        ocean.loc[i,'Region'] = 'Mid-West'
    elif row['State'] in northeast:
        ocean.loc[i,'Region'] = 'North-East'
    elif row['State'] in south:
        ocean.loc[i,'Region'] = 'South'

In [120]:
ocean[['Lat', 'Long']] = ocean.GPS.str.split(",", expand = True)
ocean.head()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Year,Month,Weekday,Day,Landfill,Recycle,Compost,Region,Lat,Long
0,86,"Cuyahoga County, OH, USA",Ohio,United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",2014-12-22,NaN,1.0,0.0,...,2014.0,12.0,0.0,22.0,1,0,0,Mid-West,41.49742,-81.56505
1,87,"Fairfax County, VA, USA",Virginia,United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",2014-12-24,NaN,1.0,0.0,...,2014.0,12.0,2.0,24.0,1,3,1,South,38.87456,-77.24428
2,92,"Washington, DC, USA",District of Columbia,United States,"38.90733, -77.04405","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,2015.0,2.0,3.0,19.0,1,1,0,South,38.90733,-77.04405
3,93,"Washington, DC, USA",District of Columbia,United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,2015.0,2.0,3.0,19.0,2,12,0,South,38.90733,-77.0441
4,94,"Washington, DC, USA",District of Columbia,United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,2015.0,2.0,3.0,19.0,2,12,0,South,38.90733,-77.0441

In [121]:
ocean['Region'].value_counts()

South         16826
West          12792
North-East     4344
Mid-West       1610
Name: Region, dtype: int64